server:
  port: 8088

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: mybatis/**/*Mapper.xml
  typeAliasesPackage: com.ben.test.entity

spring:
  datasource:
    mysql:
      write:
        type: com.zaxxer.hikari.HikariDataSource
        jdbcUrl: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8&useSSL=true
        username: write
        password: write
        driverClassName: com.mysql.jdbc.Driver
      read:
        type: com.zaxxer.hikari.HikariDataSource
        jdbcUrl: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8&useSSL=true
        username: read
        password: read
        driverClassName: com.mysql.jdbc.Driver